load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "libB1",
    srcs = ["LibB.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//libC/src/java/libC"
    ],
)

java_library(
    name = "libB2",
    srcs = ["LibB.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//libC/src/java/libC"
    ],
)
