load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "xd2",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    tags = ["manual"],
    deps = [
        "//src/xd3",
    ],
)
