load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "xd1",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/xd2",
        "//src/xd3",
    ],
)
